<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../JevSharp/JevSharp.csproj" />
    <ProjectReference Include="../../JevSharp.Core/JevSharp.Core.csproj" />
    <ProjectReference Include="../../JevSharp.Abstractions/JevSharp.Abstractions.csproj" />
  </ItemGroup>
</Project>
