<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <Description>HTTP clients and TypeSafe, OpenRouter, and Vercel adapters for JevSharp.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../JevSharp.Abstractions/JevSharp.Abstractions.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
</Project>
